# Use 1openjdk17
# FROM adoptopenjdk/openjdk17:alpine
# FROM openjdk:17-jdk-alpine
FROM maven:3.8-openjdk-18 AS build

EXPOSE 8888

# Working directory
WORKDIR /app

# Add .jar file generated during compilation
COPY target/ms-catalog-0.0.1-SNAPSHOT.jar /app/ms-catalog.jar

# Exec command to run the app
CMD ["java", "-jar", "ms-catalog.jar"]
