spring:
  cloud:
    config:
      enabled: false
  application:
    name: ms-catalog
  datasource:
    url: jdbc:mysql://localhost:3307/costumemania
    username: costumemania
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: false

server:
  port: 8080